export const RECENT_REQUEST_TABLE_BODY = [
  {
    id: 1,
    staffInitials: "JD",
    staffName: "John",
    staffLastname: "Doe",
    roomNumber: "302",
    request: "Extra towels",
    time: "10m",
    status: "New",
  },
  {
    id: 2,
    staffInitials: "AS",
    staffName: "Alice",
    staffLastname: "Smith",
    roomNumber: "505",
    request: "Late checkout",
    time: "25m",
    status: "Review",
  },
  {
    id: 3,
    staffInitials: "MR",
    staffName: "Michael",
    staffLastname: "Ross",
    roomNumber: "104",
    request: "Room service - Lunch",
    time: "1h",
    status: "In Progress",
  },
  {
    id: 4,
    staffInitials: "EW",
    staffName: "Elena",
    staffLastname: "Wood",
    roomNumber: "208",
    request: "Taxi booking",
    time: "2h",
    status: "Completed",
  },
];
