export const STAFF_TABLE_HEADER = [
  { id: 1, label: "Full Name" },
  { id: 2, label: "Department" },
  { id: 3, label: "Shift" },
  { id: 4, label: "Shift Status" },
  { id: 5, label: "Account Status" },
  { id: 6, label: "" },
];

export const STAFF_DATA = [
  {
    id: 1,
    fullName: "Sarah Jenkins",
    email: "sarah@episode.com",
    department: "Front Desk",
    shift: "morning",
    isOnShift: false,
    accountStatus: "active",
  },
  {
    id: 2,
    fullName: "Emma Wilson",
    email: "emma.w@episode.com",
    department: "Housekeeping",
    shift: "morning",
    isOnShift: true,
    accountStatus: "active",
  },
  {
    id: 3,
    fullName: "Michael Brown",
    email: "michael.b@episode.com",
    department: "Maintenance",
    shift: "night",
    isOnShift: true,
    accountStatus: "active",
  },
  {
    id: 4,
    fullName: "Olivia Davis",
    email: "olivia.d@episode.com",
    department: "Front Desk",
    shift: "night",
    isOnShift: false,
    accountStatus: "disabled",
  },
  {
    id: 5,
    fullName: "James Taylor",
    email: "james.t@episode.com",
    department: "Security",
    shift: "night",
    isOnShift: true,
    accountStatus: "active",
  },
  {
    id: 6,
    fullName: "Sophia Martinez",
    email: "sophia.m@episode.com",
    department: "Housekeeping",
    shift: "not assigned",
    isOnShift: false,
    accountStatus: "invited",
  },
  {
    id: 7,
    fullName: "Daniel Anderson",
    email: "daniel.a@episode.com",
    department: "Maintenance",
    shift: "not assigned",
    isOnShift: false,
    accountStatus: "disabled",
  },
];
